# Generated by Django 2.1 on 2018-10-26 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SHJ', '0003_auto_20181026_1525'),
    ]

    operations = [
    ]
