# Generated by Django 2.1 on 2018-10-26 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SHJ', '0004_auto_20181026_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='active',
            field=models.BooleanField(default=False, verbose_name='是否激活'),
        ),
    ]
