# Generated by Django 2.1.2 on 2018-10-05 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SHJ', '0004_auto_20181005_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='created_age',
            field=models.CharField(max_length=20, verbose_name='创建年代'),
        ),
    ]
