# Generated by Django 2.1 on 2018-10-26 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SHJ', '0005_auto_20181026_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='active',
            field=models.BooleanField(default=False, verbose_name='显示评论'),
        ),
    ]
