# Generated by Django 2.1 on 2018-10-29 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SHJ', '0006_auto_20181005_1543'),
        ('SHJ', '0006_auto_20181026_1545'),
    ]

    operations = [
    ]
