# Generated by Django 2.1 on 2018-11-30 15:04

from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('SHJ', '0007_merge_20181029_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='comment_num',
            field=models.PositiveIntegerField(default=0, verbose_name='评论数'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=mdeditor.fields.MDTextField(max_length=250, verbose_name='评论内容'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='文章评论', to='SHJ.Content', verbose_name='评论文章'),
        ),
    ]
