# Generated by Django 2.1 on 2018-12-06 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SHJ', '0008_auto_20181130_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='img',
            field=models.ImageField(default='/contentimages/default.jpg', max_length=255, null=True, upload_to='media/contentimages/', verbose_name='封面图'),
        ),
    ]
