# Generated by Django 2.1 on 2018-12-06 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SHJ', '0009_content_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='img',
            field=models.ImageField(default='/contentimages/default.jpg', max_length=255, null=True, upload_to='contentimages/', verbose_name='封面图'),
        ),
    ]
